### ISSUE TITLE
Develop a text-mining error feedback collection system

### ISSUE THREAD

**Issue by bill-baumgartner** [NCATSTranslator/Text-Mining-Provider-Roadmap#36]
**Description**
Design and implement an error-reporting system that facilitates user reporting of text-mining errors. The feedback system should be closely aligned with the relation annotation tool described in Issue #31.

- [ ] Define requirements for the error-reporting system [Issue #32]
- [ ] Reach out to Translator community to see if others are designing feedback collection systems [Issue #33]
- [ ] Design error-reporting system [Issue #34]
- [ ] Implement error-reporting system [Issue #35]
